### PR TITLE
Add proper UI elements to the Dashboard Home page

### PR DESCRIPTION
**Pull request by Abhinandan-4321**
Fixed the UI as per said in the description. #67

### CODE REVIEW

**Comment by Abhinandan-4321** [comment]
You can now review this PR.

**Comment by ananyatewari** [comment]
@CodiumAI-Agent /review

**Comment by ananyatewari** [comment]
@CodiumAI-Agent /review

**Comment by Abhinandan-4321** [comment]
Is there any change you would like me to work upon?

**Comment by ananyatewari** [comment]
PR is making use of Tailwind CSS along with plain CSS files. So far there are no inconsistencies that should be taken care of.

Merging with main branch.

**Pull request merged**
